---
title: "Fishery definition for YFT in dolphin sets"
author: "Haikun Xu"
date: "`r Sys.Date()`"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      fig.height = 8,
                      fig.width = 12)
```

```{r load raw data and library}
library(FishFreqClustering)
library(FishFreqTree)
library(tidyverse)

directory <- "D:/OneDrive - IATTC/IATTC/2024/Irregular clustering/YFT DEL/"
setwd(directory)

Raw <- read.csv("yft_lf_2000_to_2022.csv")
Raw$quarter = ceiling(Raw$month / 3)
Raw$lat = Raw$lat.5deg + 2.5
Raw$lon = Raw$lon.5deg - 2.5
```

```{r prepare the dataset for the clustering analysis}
LF.DEL <- Raw %>% filter(class == 6, setype == 1) # 1=DEL; 4=NOA; 5=OBJ

LF <- LF.DEL[, c("year", "quarter", "lat", "lon", paste0("X", 1:201))] %>%
  group_by(lat, lon) %>%
  mutate(N = length(unique(paste0(year, "-", quarter)))) %>%
  filter(N > 3, lat > -10) # remove the cells with less than 4 quarters of data since 2000

bins <- seq(1, 201, 1) # data length bins
new_bins <- seq(61, 200, 1) # bins to be used in the clustering analysis

# first aggregate the raw LF to the new bins by quarter
LF1 <- lf.aggregate(LF, fcol = 5, lcol = 205, bins, new_bins, LengthOnly = FALSE)

# Chekcing the data by making two plots
bins <- new_bins # use the new bins
nbins <- length(bins)
fcol = 5
lcol = 4 + length(bins)
save_dir=directory

make.meanl.map(LF1, fcol, lcol, bins, save_dir, width = 10, height = 10)
make.lf.map(LF1, fcol, lcol, bins, save_dir)

Area <- read.csv("D:/OneDrive - IATTC/IATTC/2024/Irregular clustering/YFT DEL/cluster_YFT2.csv")
LF1 <- left_join(LF1, Area)
```

```{r catch}
cae <- BSE::read.cae.f("D:/OneDrive - IATTC/IATTC/2024/SAC15/PS Database/", "CAE-LatLon2000-2023.txt",2000,2023)

YFT_DEL_catch <- cae %>%
  filter(setype == 1, class == 6) %>%
  rename(lat = latc5, lon = lonc5) %>%
  group_by(lat, lon) %>%
  summarise(Catch = sum(sum.trop.tunas)/1000)

wmap <- map_data("world")
ggplot(data = YFT_DEL_catch) +
  geom_tile(aes(x = lon, y = lat, fill = Catch), color = "black") +
    scale_fill_gradient(
    low = "white",
    high = "red",
    na.value = "white",
    limits = c(0, max(YFT_DEL_catch$Catch))
  ) +
  geom_polygon(
    data = wmap,
    aes(long, lat, group = group),
    fill = "black",
    colour = "white",
    lwd = 0.5
  ) +
  coord_quickmap(ylim = c(min(YFT_DEL_catch$lat), max(YFT_DEL_catch$lat)), xlim = c(min(YFT_DEL_catch$lon), max(YFT_DEL_catch$lon))) +
  theme_bw()
```

```{r a2}
# divide the LF by the mean LF for the year-quarter
LF1_a2 <- LF1 %>% filter(area == 2)

mmd <- LF1_a2[,c(1,3:lcol)] # mmd is the input data for the clustering analysis - it should have year, lat, lon, and bin numbers

# setting up input data frames for clustering algorithm
temp = packbylatlon(mmd, 5, 5, nbins)  # aggregate the input LF across time for each grid cell

packedmmd3 = temp$table1
packedpdf3 = topdf(packedmmd3, 4, 3 + nbins)
# packedcdf3 = tocdf(packedpdf3, 4, 3 + nbins)
mmdt = packedmmd3[packedmmd3[, 4 + nbins] > 0,]
mmdtpdf = packedpdf3[packedmmd3[, 4 + nbins] > 0,] # PDF sums to 1 for each grid
mmdtpdf[, 4 + nbins] = mmdt[, 4 + nbins]
# mmdtcdf = packedcdf3[packedmmd3[, 4 + nbins] > 0,]
# mmdtcdf[, 4 + nbins] = mmdt[, 4 + nbins]

names(mmdtpdf)[2:3] <- c("lat", "lon")
mmdtpdf$Number <- 1:nrow(mmdtpdf)
mmdfpdf_catch <- left_join(mmdtpdf, YFT_DEL_catch)

rrs = mmdfpdf_catch$Catch # sample size

# check grid ID
ggplot(data = mmdfpdf_catch) +
  geom_polygon(
    data = wmap,
    aes(long, lat, group = group),
    fill = "black",
    colour = "white",
    lwd = 0.5
  ) +
  geom_text(aes(x = lon, y = lat, label = Number), color = "red", size = 5) +
  coord_quickmap(ylim = c(min(mmdfpdf_catch$lat), max(mmdfpdf_catch$lat)), xlim = c(min(mmdfpdf_catch$lon), max(mmdfpdf_catch$lon))) +
  ggtitle("Grid ID") +
  theme_bw()

densmatx = matrix(0, nrow(mmdt), 420)
densmaty = matrix(0, nrow(mmdt), 420)
for(i in 1:nrow(mmdt)) {
  weightvec = t(mmdt[i, 4:(3 + nbins)])
  weightvec = weightvec / sum(weightvec)
  tempmmd = density(seq(0.61, 2.00, 0.01), weights = weightvec, bw = 0.05)
  ii <- which(tempmmd$x>=0.61 & tempmmd$x<=2.00)
  densmatx[i, ] = tempmmd$x[ii]
  densmaty[i, ] = tempmmd$y[ii]
}

# run distributional clustering with adjacency criterion
adjmat <- adjinf(mmdtpdf[, 2], mmdtpdf[, 3], mindist = 5 * sqrt(2)) # the matrix specifying adjacency 

alydens.spatial23 <-
  hclust.regionsmm(
    as.matrix(densmaty),
    adj = TRUE, # adjacent areas
    adjmat = adjmat,
    rr = rrs # rr is the weighting factor; equal weighting is used in this case
  )


teststat <- heterodist(
  alydens.spatial23$merges,
  alydens.spatial23$distseq,
  densmatx[1,],
  densmaty,
  rrs,
  doko = c(1, 25),
  BB = 100,
  bins = seq(0.61, 2.00, 0.01)
)

catch_prop <- rep(0, nrow(teststat$statmat))
for (i in 1:nrow(teststat$statmat)) {
  Cells <- teststat$childnodes[i][[1]]
  catch_prop[i] <- sum(mmdfpdf_catch$Catch[Cells]) / sum(mmdfpdf_catch$Catch)
}

MJS_statistics <- data.frame(cbind(1:nrow(teststat$statmat), teststat$statmat[,4], round(catch_prop,2)))
names(MJS_statistics) <- c("Node_Number", "STD_distance", "Catch_Proportion")
# write.csv(MJS_statistics, file = "MJS distance (Fishery Structure).csv", row.names = FALSE)


# draw density curves by cluster
final_nodes <- find_clusters(MJS_statistics, distance_threshold = 50, catch_threshold = 0.50)
MJS_statistics[final_nodes,]

# Look at the tree structure
cplotu(alydens.spatial23$merges, alydens.spatial23$distseq, hopt = 'dist', plotnum = final_nodes)

temp2 <- rep(1, nrow(mmdt))
for (i in 2:length(final_nodes)) {
  temp2[teststat$childnodes[final_nodes[i]][[1]]] <- i
}

cluster <- cbind(mmdt[,2:3], factor(temp2), round(mmdfpdf_catch$Catch,0))
names(cluster) <- c("lat", "lon", "cell", "Weight")
# write.csv(cluster, file = paste0(save_dir, "cluster_YFT", kk, ".csv"), row.names = FALSE)

# # map of clusters
ggplot(data = cluster) +
  geom_tile(aes(x = lon, y = lat, fill = cell), color = "black") +
  geom_polygon(
    data = wmap,
    aes(long, lat, group = group),
    fill = "black",
    colour = "white",
    lwd = 0.5
  ) +
  geom_text(aes(x = lon, y = lat, label = Weight),
            color = "white",
            size = 7,
            ) +
  coord_quickmap(ylim = c(min(cluster$lat), max(cluster$lat)), xlim = c(min(cluster$lon), max(cluster$lon))) +
  theme_bw()
# ggsave(file = paste0(save_dir, "Clustering_map.png"), h = 5, w= 8)

colcol = rep(c(2, 3, 4, 5, 6, 7, 8), 3)
densy_df <- clusthistd3(kk = length(final_nodes), colseq = temp2 + 1, colcol, plot = FALSE)

ggplot(data = densy_df) +
  geom_line(aes(x = Length, y = Density, color = Cell), linewidth = 2) +
  theme_bw()
```

```{r a3}
# divide the LF by the mean LF for the year-quarter
LF1_a3 <- LF1 %>% filter(area == 3)

mmd <- LF1_a3[,c(1,3:lcol)] # mmd is the input data for the clustering analysis - it should have year, lat, lon, and bin numbers

# setting up input data frames for clustering algorithm
temp = packbylatlon(mmd, 5, 5, nbins)  # aggregate the input LF across time for each grid cell

packedmmd3 = temp$table1
packedpdf3 = topdf(packedmmd3, 4, 3 + nbins)
# packedcdf3 = tocdf(packedpdf3, 4, 3 + nbins)
mmdt = packedmmd3[packedmmd3[, 4 + nbins] > 0,]
# rrs = mmdt[, 4 + nbins] # sample size
mmdtpdf = packedpdf3[packedmmd3[, 4 + nbins] > 0,] # PDF sums to 1 for each grid
mmdtpdf[, 4 + nbins] = mmdt[, 4 + nbins]
# mmdtcdf = packedcdf3[packedmmd3[, 4 + nbins] > 0,]
# mmdtcdf[, 4 + nbins] = mmdt[, 4 + nbins]

names(mmdtpdf)[2:3] <- c("lat", "lon")
mmdtpdf$Number <- 1:nrow(mmdtpdf)
mmdfpdf_catch <- left_join(mmdtpdf, YFT_DEL_catch)

rrs = mmdfpdf_catch$Catch # sample size

# check grid ID
ggplot(data = mmdfpdf_catch) +
  geom_polygon(
    data = wmap,
    aes(long, lat, group = group),
    fill = "black",
    colour = "white",
    lwd = 0.5
  ) +
  geom_text(aes(x = lon, y = lat, label = Number), color = "red", size = 5) +
  coord_quickmap(ylim = c(min(mmdfpdf_catch$lat), max(mmdfpdf_catch$lat)), xlim = c(min(mmdfpdf_catch$lon), max(mmdfpdf_catch$lon))) +
  ggtitle("Grid ID") +
  theme_bw()

densmatx = matrix(0, nrow(mmdt), 420)
densmaty = matrix(0, nrow(mmdt), 420)
for(i in 1:nrow(mmdt)) {
  weightvec = t(mmdt[i, 4:(3 + nbins)])
  weightvec = weightvec / sum(weightvec)
  tempmmd = density(seq(0.61, 2.00, 0.01), weights = weightvec, bw = 0.05)
  ii <- which(tempmmd$x>=0.61 & tempmmd$x<=2.00)
  densmatx[i, ] = tempmmd$x[ii]
  densmaty[i, ] = tempmmd$y[ii]
}

# run distributional clustering with adjacency criterion
adjmat <- adjinf(mmdtpdf[, 2], mmdtpdf[, 3], mindist = 5 * sqrt(2)) # the matrix specifying adjacency
adjmat[4,8] <- 0
adjmat[8,4] <- 0

alydens.spatial23 <-
  hclust.regionsmm(
    as.matrix(densmaty),
    adj = TRUE, # adjacent areas
    adjmat = adjmat,
    rr = rrs # rr is the weighting factor; equal weighting is used in this case
  )


teststat <- heterodist(
  alydens.spatial23$merges,
  alydens.spatial23$distseq,
  densmatx[1,],
  densmaty,
  rrs,
  doko = c(1, 25),
  BB = 100,
  bins = seq(0.61, 2.00, 0.01)
)

catch_prop <- rep(0, nrow(teststat$statmat))
for (i in 1:nrow(teststat$statmat)) {
  Cells <- teststat$childnodes[i][[1]]
  catch_prop[i] <- sum(mmdfpdf_catch$Catch[Cells]) / sum(mmdfpdf_catch$Catch)
}

MJS_statistics <- data.frame(cbind(1:nrow(teststat$statmat), teststat$statmat[,4], round(catch_prop,2)))
names(MJS_statistics) <- c("Node_Number", "STD_distance", "Catch_Proportion")
# write.csv(MJS_statistics, file = "MJS distance (Fishery Structure).csv", row.names = FALSE)


# draw density curves by cluster
final_nodes <- find_clusters(MJS_statistics, distance_threshold = 20, catch_threshold = 0.4)
MJS_statistics[final_nodes,]

# Look at the tree structure
cplotu(alydens.spatial23$merges, alydens.spatial23$distseq, hopt = 'dist', plotnum = final_nodes)

temp2 <- rep(1, nrow(mmdt))
for (i in 2:length(final_nodes)) {
  temp2[teststat$childnodes[final_nodes[i]][[1]]] <- i
}

cluster <- cbind(mmdt[,2:3], factor(temp2), round(mmdfpdf_catch$Catch,0))
names(cluster) <- c("lat", "lon", "cell", "weight")
# write.csv(cluster, file = paste0(save_dir, "cluster_YFT", kk, ".csv"), row.names = FALSE)

# # map of clusters
ggplot(data = cluster) +
  geom_tile(aes(x = lon, y = lat, fill = cell), color = "black") +
  geom_polygon(
    data = wmap,
    aes(long, lat, group = group),
    fill = "black",
    colour = "white",
    lwd = 0.5
  ) +
  geom_text(aes(x = lon, y = lat, label = weight),
            color = "white",
            size = 7,
            ) +
  coord_quickmap(ylim = c(min(cluster$lat), max(cluster$lat)), xlim = c(min(cluster$lon), max(cluster$lon))) +
  theme_bw()
# ggsave(file = paste0(save_dir, "Clustering_map.png"), h = 5, w= 8)

colcol = rep(c(2, 3, 4, 5, 6, 7, 8), 3)
densy_df <- clusthistd3(kk = length(final_nodes), colseq = temp2 + 1, colcol, plot = FALSE)

ggplot(data = densy_df) +
  geom_line(aes(x = Length, y = Density, color = Cell), linewidth = 2) +
  theme_bw()
```

```{r a1}
# divide the LF by the mean LF for the year-quarter
LF1_a1 <- LF1 %>% filter(area == 4)
LF2 <- lf.demean(LF1_a1, fcol, lcol, bins)

mmd <- LF2[,c(2,4:(lcol+1))] # mmd is the input data for the clustering analysis - it should have year, lat, lon, and bin numbers

# setting up input data frames for clustering algorithm
temp = packbylatlon(mmd, 5, 5, nbins)  # aggregate the input LF across time for each grid cell

packedmmd3 = temp$table1
packedpdf3 = topdf(packedmmd3, 4, 3 + nbins)
# packedcdf3 = tocdf(packedpdf3, 4, 3 + nbins)
mmdt = packedmmd3[packedmmd3[, 4 + nbins] > 0,]
rrs = mmdt[, 4 + nbins] # sample size
mmdtpdf = packedpdf3[packedmmd3[, 4 + nbins] > 0,] # PDF sums to 1 for each grid
mmdtpdf[, 4 + nbins] = mmdt[, 4 + nbins]
# mmdtcdf = packedcdf3[packedmmd3[, 4 + nbins] > 0,]
# mmdtcdf[, 4 + nbins] = mmdt[, 4 + nbins]

names(mmdtpdf)[2:3] <- c("lat", "lon")
mmdtpdf$Number <- 1:nrow(mmdtpdf)
mmdfpdf_catch <- left_join(mmdtpdf, YFT_DEL_catch)

rrs = mmdfpdf_catch$Catch # sample size

# check grid ID
ggplot(data = mmdfpdf_catch) +
  geom_polygon(
    data = wmap,
    aes(long, lat, group = group),
    fill = "black",
    colour = "white",
    lwd = 0.5
  ) +
  geom_text(aes(x = lon, y = lat, label = Number), color = "red", size = 5) +
  coord_quickmap(ylim = c(min(mmdfpdf_catch$lat), max(mmdfpdf_catch$lat)), xlim = c(min(mmdfpdf_catch$lon), max(mmdfpdf_catch$lon))) +
  ggtitle("Grid ID") +
  theme_bw()

densmatx = matrix(0, nrow(mmdt), 420)
densmaty = matrix(0, nrow(mmdt), 420)
for(i in 1:nrow(mmdt)) {
  weightvec = t(mmdt[i, 4:(3 + nbins)])
  weightvec = weightvec / sum(weightvec)
  tempmmd = density(seq(0.61, 2.00, 0.01), weights = weightvec, bw = 0.05)
  ii <- which(tempmmd$x>=0.61 & tempmmd$x<=2.00)
  densmatx[i, ] = tempmmd$x[ii]
  densmaty[i, ] = tempmmd$y[ii]
}

# run distributional clustering with adjacency criterion
adjmat <- adjinf(mmdtpdf[, 2], mmdtpdf[, 3], mindist = 5 * sqrt(2)) # the matrix specifying adjacency 

alydens.spatial23 <-
  hclust.regionsmm(
    as.matrix(densmaty),
    adj = TRUE, # adjacent areas
    adjmat = adjmat,
    rrs)


teststat <- heterodist(
  alydens.spatial23$merges,
  alydens.spatial23$distseq,
  densmatx[1,],
  densmaty,
  rrs,
  doko = c(1, 8),
  BB = 100,
  bins = seq(0.61, 2.00, 0.01)
)

catch_prop <- rep(0, nrow(teststat$statmat))
for (i in 1:nrow(teststat$statmat)) {
  Cells <- teststat$childnodes[i][[1]]
  catch_prop[i] <- sum(mmdfpdf_catch$Catch[Cells]) / sum(mmdfpdf_catch$Catch)
}

MJS_statistics <- data.frame(cbind(1:nrow(teststat$statmat), teststat$statmat[,4], round(catch_prop,2)))
names(MJS_statistics) <- c("Node_Number", "STD_distance", "Catch_Proportion")
# write.csv(MJS_statistics, file = "MJS distance (Fishery Structure).csv", row.names = FALSE)


# draw density curves by cluster
final_nodes <- find_clusters(MJS_statistics, distance_threshold = 100, catch_threshold = 0.2)

# Look at the tree structure
cplotu(alydens.spatial23$merges, alydens.spatial23$distseq, hopt = 'dist', plotnum = final_nodes)

temp2 <- rep(1, nrow(mmdt))
for (i in 2:length(final_nodes)) {
  temp2[teststat$childnodes[final_nodes[i]][[1]]] <- i
}

cluster <- cbind(mmdt[,2:3], factor(temp2), round(mmdfpdf_catch$Catch,0))
names(cluster) <- c("lat", "lon", "cell", "Weight")
# write.csv(cluster, file = paste0(save_dir, "cluster_YFT", kk, ".csv"), row.names = FALSE)

# # map of clusters
ggplot(data = cluster) +
  geom_tile(aes(x = lon, y = lat, fill = cell), color = "black") +
  geom_polygon(
    data = wmap,
    aes(long, lat, group = group),
    fill = "black",
    colour = "white",
    lwd = 0.5
  ) +
  geom_text(aes(x = lon, y = lat, label = Weight),
            color = "white",
            size = 7,
            ) +
  coord_quickmap(ylim = c(min(cluster$lat), max(cluster$lat)), xlim = c(min(cluster$lon), max(cluster$lon))) +
  theme_bw()
# ggsave(file = paste0(save_dir, "Clustering_map.png"), h = 5, w= 8)

colcol = rep(c(2, 3, 4, 5, 6, 7, 8), 3)
densy_df <- clusthistd3(kk = length(final_nodes), colseq = temp2 + 1, colcol, plot = FALSE)

ggplot(data = densy_df) +
  geom_line(aes(x = Length, y = Density, color = Cell), linewidth = 2) +
  theme_bw()
```